# Generated by Django 4.0.4 on 2022-05-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='employee',
            new_name='user',
        ),
    ]
