# Generated by Django 4.0.4 on 2022-05-29 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_alter_menu_kategori_alter_menu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('no_meja', models.IntegerField(default=0)),
                ('kode_menu', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
