# Generated by Django 4.0.4 on 2022-05-26 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_menu_kategori_alter_menu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_code', models.CharField(max_length=200)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('pay', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sales')),
            ],
        ),
    ]
