# Generated by Django 4.0.4 on 2022-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='no_meja',
            field=models.IntegerField(default=0),
        ),
    ]
