# Generated by Django 4.0.4 on 2022-05-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_kategori_alter_menu_status'),
        ('pos', '0002_alter_sales_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
