# Generated by Django 4.0.4 on 2022-05-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_sales_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='kode_menu',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='status',
        ),
    ]
