# Generated by Django 4.0.4 on 2022-05-23 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=200, null=True)),
                ('menu', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(blank=True, choices=[('Makanan', 'Makanan'), ('Minuman', 'Minuman'), ('Snacks', 'Snacks')], max_length=200, null=True)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Tersedia', 'Tersedia'), ('Habis', 'Habis')], default='Tersedia', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
