# Generated by Django 4.0.4 on 2022-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Snacks', 'Snacks')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Tersedia', max_length=200, null=True),
        ),
    ]
